package com.cylmms.pojo;

import lombok.ToString;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table gp
 */
@ToString
public class Gp {
    /**
     * Database Column Remarks:
     *   编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gp.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   团组织名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gp.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   所属上级团组织
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gp.superior
     *
     * @mbg.generated
     */
    private String superior;

    /**
     * Database Column Remarks:
     *   组织类别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gp.category
     *
     * @mbg.generated
     */
    private String category;

    /**
     * Database Column Remarks:
     *   所属行业
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gp.industry
     *
     * @mbg.generated
     */
    private String industry;

    /**
     * Database Column Remarks:
     *   团员人数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gp.mem_num
     *
     * @mbg.generated
     */
    private Integer memNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gp.id
     *
     * @return the value of gp.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gp.id
     *
     * @param id the value for gp.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gp.name
     *
     * @return the value of gp.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gp.name
     *
     * @param name the value for gp.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gp.superior
     *
     * @return the value of gp.superior
     *
     * @mbg.generated
     */
    public String getSuperior() {
        return superior;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gp.superior
     *
     * @param superior the value for gp.superior
     *
     * @mbg.generated
     */
    public void setSuperior(String superior) {
        this.superior = superior == null ? null : superior.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gp.category
     *
     * @return the value of gp.category
     *
     * @mbg.generated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gp.category
     *
     * @param category the value for gp.category
     *
     * @mbg.generated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gp.industry
     *
     * @return the value of gp.industry
     *
     * @mbg.generated
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gp.industry
     *
     * @param industry the value for gp.industry
     *
     * @mbg.generated
     */
    public void setIndustry(String industry) {
        this.industry = industry == null ? null : industry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gp.mem_num
     *
     * @return the value of gp.mem_num
     *
     * @mbg.generated
     */
    public Integer getMemNum() {
        return memNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gp.mem_num
     *
     * @param memNum the value for gp.mem_num
     *
     * @mbg.generated
     */
    public void setMemNum(Integer memNum) {
        this.memNum = memNum;
    }
}
