package com.cylmms.pojo;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table group
 */
public class Group {
    /**
     * Database Column Remarks:
     * 编号
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     * 团组织名称
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     * 所属上级团组织
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.superior
     *
     * @mbg.generated
     */
    private String superior;

    /**
     * Database Column Remarks:
     * 组织类别
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.category
     *
     * @mbg.generated
     */
    private String category;

    /**
     * Database Column Remarks:
     * 所属行业
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.industry
     *
     * @mbg.generated
     */
    private String industry;

    /**
     * Database Column Remarks:
     * 团员人数
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.mem_num
     *
     * @mbg.generated
     */
    private Integer memNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.id
     *
     * @return the value of group.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.id
     *
     * @param id the value for group.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.name
     *
     * @return the value of group.name
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.name
     *
     * @param name the value for group.name
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.superior
     *
     * @return the value of group.superior
     * @mbg.generated
     */
    public String getSuperior() {
        return superior;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.superior
     *
     * @param superior the value for group.superior
     * @mbg.generated
     */
    public void setSuperior(String superior) {
        this.superior = superior == null ? null : superior.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.category
     *
     * @return the value of group.category
     * @mbg.generated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.category
     *
     * @param category the value for group.category
     * @mbg.generated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.industry
     *
     * @return the value of group.industry
     * @mbg.generated
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.industry
     *
     * @param industry the value for group.industry
     * @mbg.generated
     */
    public void setIndustry(String industry) {
        this.industry = industry == null ? null : industry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.mem_num
     *
     * @return the value of group.mem_num
     * @mbg.generated
     */
    public Integer getMemNum() {
        return memNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.mem_num
     *
     * @param memNum the value for group.mem_num
     * @mbg.generated
     */
    public void setMemNum(Integer memNum) {
        this.memNum = memNum;
    }
}
