package com.cylmms.pojo;

import lombok.ToString;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table member
 */
@ToString
public class Member {
    /**
     * Database Column Remarks:
     * 身份证号
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.id_card
     *
     * @mbg.generated
     */
    private String idCard;

    /**
     * Database Column Remarks:
     * 姓名
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     * 年龄
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     * Database Column Remarks:
     * 团龄
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.group_age
     *
     * @mbg.generated
     */
    private Integer groupAge;

    /**
     * Database Column Remarks:
     * 政治面貌
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.politics_status
     *
     * @mbg.generated
     */
    private String politicsStatus;

    /**
     * Database Column Remarks:
     * 民族
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.national
     *
     * @mbg.generated
     */
    private String national;

    /**
     * Database Column Remarks:
     * 团内职务
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.duty
     *
     * @mbg.generated
     */
    private String duty;

    /**
     * Database Column Remarks:
     * 所属团组织
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.affiliated
     *
     * @mbg.generated
     */
    private String affiliated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.id_card
     *
     * @return the value of member.id_card
     * @mbg.generated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.id_card
     *
     * @param idCard the value for member.id_card
     * @mbg.generated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.name
     *
     * @return the value of member.name
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.name
     *
     * @param name the value for member.name
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.age
     *
     * @return the value of member.age
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.age
     *
     * @param age the value for member.age
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.group_age
     *
     * @return the value of member.group_age
     * @mbg.generated
     */
    public Integer getGroupAge() {
        return groupAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.group_age
     *
     * @param groupAge the value for member.group_age
     * @mbg.generated
     */
    public void setGroupAge(Integer groupAge) {
        this.groupAge = groupAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.politics_status
     *
     * @return the value of member.politics_status
     * @mbg.generated
     */
    public String getPoliticsStatus() {
        return politicsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.politics_status
     *
     * @param politicsStatus the value for member.politics_status
     * @mbg.generated
     */
    public void setPoliticsStatus(String politicsStatus) {
        this.politicsStatus = politicsStatus == null ? null : politicsStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.national
     *
     * @return the value of member.national
     * @mbg.generated
     */
    public String getNational() {
        return national;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.national
     *
     * @param national the value for member.national
     * @mbg.generated
     */
    public void setNational(String national) {
        this.national = national == null ? null : national.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.duty
     *
     * @return the value of member.duty
     * @mbg.generated
     */
    public String getDuty() {
        return duty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.duty
     *
     * @param duty the value for member.duty
     * @mbg.generated
     */
    public void setDuty(String duty) {
        this.duty = duty == null ? null : duty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.affiliated
     *
     * @return the value of member.affiliated
     * @mbg.generated
     */
    public String getAffiliated() {
        return affiliated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.affiliated
     *
     * @param affiliated the value for member.affiliated
     * @mbg.generated
     */
    public void setAffiliated(String affiliated) {
        this.affiliated = affiliated == null ? null : affiliated.trim();
    }
}
