package com.cylmms.pojo;

import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user
 */
@ToString
@NoArgsConstructor
public class User {
    /**
     * Database Column Remarks:
     * 身份证号
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id_card
     *
     * @mbg.generated
     */
    private String idCard;

    /**
     * Database Column Remarks:
     * 密码
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * Database Column Remarks:
     * 姓名
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     * 职务
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.duty
     *
     * @mbg.generated
     */
    private String duty;

    /**
     * Database Column Remarks:
     * 是否超级管理员
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.super_admin
     *
     * @mbg.generated
     */
    private Integer superAdmin;

    public User(String idCard, String password) {
        this.idCard = idCard;
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id_card
     *
     * @return the value of user.id_card
     * @mbg.generated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id_card
     *
     * @param idCard the value for user.id_card
     * @mbg.generated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.duty
     *
     * @return the value of user.duty
     * @mbg.generated
     */
    public String getDuty() {
        return duty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.duty
     *
     * @param duty the value for user.duty
     * @mbg.generated
     */
    public void setDuty(String duty) {
        this.duty = duty == null ? null : duty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.super_admin
     *
     * @return the value of user.super_admin
     * @mbg.generated
     */
    public Integer getSuperAdmin() {
        return superAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.super_admin
     *
     * @param superAdmin the value for user.super_admin
     * @mbg.generated
     */
    public void setSuperAdmin(Integer superAdmin) {
        this.superAdmin = superAdmin;
    }
}
